name: 自动同步同事仓库
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 同步代码
        run: |
          git config --global user.name "Auto Sync"
          git config --global user.email "sync@github.com"
          git remote add upstream https://${{ secrets.PAT }}@github.com/xiaolishengqile/clothing_images.git
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories
          git push https://${{ secrets.PAT }}@github.com/liuyi-1222/clothing_images.git main
