name: 自动同步同事仓库
on:
  workflow_dispatch:  # 允许手动点一下同步
  schedule:
    - cron: '0 * * * *' # 每小时自动同步一次

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 同步上游仓库
        uses: wei/git-sync@v3
        with:
          source_repo: "xiaolishengqile/clothing_images"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.PAT }}
